stages:
  - build
  - test

build:ubuntu:
  image: ubuntu:rolling
  stage: build
  tags:
    - docker
  script:
    - apt-get update && apt-get install -y build-essential wget libssl-dev
    - mkdir cmake
    - wget https://github.com/Kitware/CMake/releases/download/v3.16.2/cmake-3.16.2-Linux-x86_64.sh
    - sh ./cmake-3.16.2-Linux-x86_64.sh --skip-license
    - cp bin/* /usr/bin
    - cd /builds/$CI_PROJECT_PATH
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build