stages:
  - build
  - test

build:ubuntu:
  image: ubuntu:focal
  stage: build
  tags:
    - docker
  script:
    - apt-get update && apt-get install -y build-essential cmake python3 python3-dev python3-pip python3-tk python3-numpy python3-matplotlib
    - cd /builds/$CI_PROJECT_PATH
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build