image: Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python38-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python -m pip install --upgrade pip

build_script:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - cd %APPVEYOR_BUILD_FOLDER%
  - pip install numpy matplotlib
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCXXPLOT_ENABLE_EXAMPLES=ON -DCXXPLOT_ENABLE_TESTS=ON  ..
  - cmake --build . --target ALL_BUILD --config Release

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd build
  - ctest -C Release